### ISSUE TITLE
Scope header is missing

### ISSUE THREAD

**Issue by angeldev20** [amzn/amazon-advertising-api-php-sdk#11]
When call listCampaigns,  it returns error "Scope header is missing".

**Comment by angeldev20** [comment]
Can Profile Id  be only got from SandBox?
SandBox's Profile Id is working on live( not SandBox)?

**Comment by dbrent-amazon** [comment]
Hello,

Integration issues are handled via Jira service desk. If you have onboarded with the API you should have an account.

https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2

Brent
