### ISSUE TITLE
Where do you find your accessToken or refreshToken?

### ISSUE THREAD

**Issue by xmadscientist** [amzn/amazon-advertising-api-php-sdk#4]
As the title says, **where do you find your accessToken or refreshToken?**

**Comment by dbrent-amazon** [comment]
Hello,

Access and refresh tokens come from Login with Amazon as described in the [Getting Started Guide](https://images-na.ssl-images-amazon.com/images/G/01/AdProductsWebsite/downloads/Amazon_Advertising_API_Getting_Started_Guide._TTH_.pdf) for the API.

You'll need to [register](https://advertising.amazon.com/API) for access to the API, however.

**Comment by xmadscientist** [comment]
I've sent multiple applications for registration but I'm not getting a reply. How do you get access?

**Comment by dbrent-amazon** [comment]
I do not control that process. There is a vetting process and it can take some time.

**Comment by dbrent-amazon** [comment]
Closing this issue as it cannot be resolved here.
