### ISSUE TITLE
Where to get accessToken/refreshToken?

### ISSUE THREAD

**Issue by xmadscientist** [amzn/amazon-advertising-api-php-sdk#7]
Where can we get the accessToken/refreshToken?

**Comment by dbrent-amazon** [comment]
@xmadscientist have you completed onboarding with the API? If so, have a look here: https://advertising.amazon.com/API/docs/guides/authorization

If not, you will need to complete onboarding prior to trying to make any API calls.

**Comment by xmadscientist** [comment]
Great, thanks for the help.
