### ISSUE TITLE
Error getting Refresh token

### ISSUE THREAD

**Issue by xmadscientist** [amzn/amazon-advertising-api-php-sdk#8]
While going thru the Authorization process, we keep getting an error when trying to retrieve the refresh + access token. 

`{"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}`

After being redirected from LwA, we copy the Auth code exactly from the redirect_uri query string into our serversided call with cURL in order to get the refresh token, but we keep getting this error. Any help or suggestions?

**Comment by dbrent-amazon** [comment]
@xmadscientist if you have officially onboarded with the API you should have had a Jira support account created. Please open a ticket via Jira for integration issues.

**Comment by xmadscientist** [comment]
The onboarding email I received from the API team unfortunately did not include or mention anything regarding Jira.

**Comment by dbrent-amazon** [comment]
Did you complete the onboarding process by clicking the link in the email? i.e. accepted license and whitelisted a client Id? Can you please share the client Id you whitelisted?

**Comment by xmadscientist** [comment]
Yes, I have. I accepted the agreement and whitelisted the client ID. Here is the client ID that was whitelisted: amzn1.application-oa2-client.4246e0f086e441259742c758f63ca0bf

**Comment by dbrent-amazon** [comment]
Thanks. I've forwarded this to our onboarding team. They are in EU so I probably won't hear back until tomorrow.

In the meantime, can you share the POST body here?

**Comment by xmadscientist** [comment]
`curl -X POST -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8" --data "grant_type=authorization_code&code=ANiulLrNladHYQyyNylE&redirect_uri=https://ppcology.io&client_id=amzn1.application-oa2-client.4246e0f086e441259742c758f63ca0bf&client_secret=9c....7cabeb3" https://api.amazon.com/auth/o2/token`

That's what I have. Of course, we have tried with different auth codes since they expire every 5 minutes. Is there anything wrong with this?

**Comment by dbrent-amazon** [comment]
The request looks perfectly fine. Does your consent link have the same client Id? Other than that, "invalid_grant" could only mean the code has expired.

**Comment by xmadscientist** [comment]
Okay great to hear. What do you mean by consent link?

**Comment by dbrent-amazon** [comment]
The consent link is generated then clicked to invoke the Login with Amazon where credentials are entered. From there, we get to the step you are on. Once consent is granted (via LwA) the user is redirected to your backend where the code is passed in the query parameters.

The consent link that was clicked to kick off this entire process must use the same client Id.

**Comment by xmadscientist** [comment]
Okay, I just checked the consent link and it does indeed have the same client ID. Is there anything else you can think of that might be throwing us off?

**Comment by dbrent-amazon** [comment]
That's all it could be. The authentication process is Login with Amazon (as you know) and according to their developer guide, invalid_grant means _The authorization code is invalid, expired, revoked, or was issued to a different client_id_.

https://developer.amazon.com/docs/login-with-amazon/authorization-code-grant.html

I assume the code isn't expired by the time you try the call since you knew how long they lasted so I ruled that out.

**Comment by xmadscientist** [comment]
Hmm.. so why is it still giving me the invalid_grant error? :(

**Comment by dbrent-amazon** [comment]
I do not know. There are no other reasons it can be as far as I know. The Login with Amazon team would be able to help troubleshoot but I've never seen this issue have to be escalated to that point. Is there a chance your consent link had a different client Id and was later changed to what you have now? Have you tried clicking the consent link again to try again?

**Comment by xmadscientist** [comment]
Yes, I have tried clicking the consent link again and I also double checked the client ID in it.

**Comment by xmadscientist** [comment]
I tried contacting the API team about it but they rarely answer my emails!

**Comment by angeldev20** [comment]
Hi,
How to get token to config the client library?

**Comment by dbrent-amazon** [comment]
Hello,

Integration issues are handled via Jira service desk. If you have onboarded with the API you should have an account.

Brent
