### ISSUE TITLE
Error on accessing anything from Amazon

### ISSUE THREAD

**Issue by xyrintech** [amzn/amazon-advertising-api-php-sdk#9]
I am trying to access the listProfiles but this gives me 401 error. 

I am generating a valid access token and refresh token. doRefresh works completely fine and returns a new token but unable to fetch the data with the access token generated.

**Comment by dbrent-amazon** [comment]
If you have onboarded with the API you should have a Jira account. Please raise a ticket there.

**Comment by xyrintech** [comment]
Do you mean if Amazon give me the access for the API?

**Comment by dbrent-amazon** [comment]
Yes. Did you go through the onboarding process?

**Comment by xyrintech** [comment]
I have filled out the form a week ago but Amazon has not responded yet.

**Comment by dbrent-amazon** [comment]
Until you have been onboarded (client Id whitelisted) none of these calls will work. You should wait for a response from our onboarding team in the meantime.

**Comment by xyrintech** [comment]
Sure, thanks. I really appreciate your response.

**Comment by xyrintech** [comment]
I got a response from Amazon mentioning that Amazon has given an access for this. But they did not give any access to JIRA account. 

Also, when I tried accessing the data again then it gives me same error for Authentication. 

I generated access token with refresh token and this works fine but when I access the advertising APIs then 401 i.e. Authentication Failed error comes in.

**Comment by dbrent-amazon** [comment]
Please respond to the onboarding email with a technical contact email so that they can create the account. You will also need to go through the onboarding process as well. There should be a link in the email. The link will guide you in accepting the license agreement and whitelisting a client Id.

**Comment by xyrintech** [comment]
I have gone through this on boarding process and got the access to JIRA account. Your knowledge really helps to get this done, thanks for this. 

One issue I am still struggling, I am getting 401 error (same error) and would really appreciate if you can suggest how I can get this thing work. 

Also, I am not sure and trying to understand how JIRA account is connected to my Application (developer account)? Is there anything I have to do in order to connect it?

One more question, lets say we have 2 or more applications on Amazon Developer Account. Can I use anyone of the application or I have to get the access separately for every application?
